### PR TITLE
Add `Timezone::Zone#parse_local(time_string)` method

### PR DESCRIPTION
**Pull request by AlexWayfer**

### CODE REVIEW

**Comment by panthomakos** [comment]
> But there is Zone#time_with_offset, than it's worse?

The difference is the input and the functionality the method provides. If the `parse` case is added to the gem, then an `strftime` and `strptime` method (and others) should be added for parity. But all of these methods are simply formatting of input/output values, they don't actually provide any additional benefit to the caller (like conversion to/from a timezone).

There is an additional complexity to providing multiple ways to parse input as well - in this implementation you default to returning an offset, but we should provide a non-offset version, and a version that converts from UTC to local and from local to UTC, but this is all already provided by the gem and would greatly increase the public API the gem needs to support.

**Comment by AlexWayfer** [comment]
> If the `parse` case is added to the gem, then an `strftime` and `strptime` method (and others) should be added for parity.

I don't think so. This (and others) method returns `Time`-object, on which `strftime` can be called.

> they don't actually provide any additional benefit to the caller (like conversion to/from a timezone).

Parsed string converts into `Time`-object with considering a timezone.

> There is an additional complexity to providing multiple ways to parse input as well - in this implementation you default to returning an offset, but we should provide a non-offset version

You're right, I think :pensive: 

-----

Here's my initial desire:
* I get `address` and `date-time` (in the future) fields from the user's form
* I get coordinates for received `address` via Google Maps Geocoding API, for example
* I get timezone for this coordinates
* I convert the `date-time` filed's value from the form (as a String, like a `2018-03-25 18:00`) to a `Time`-object and save it (via ORM) into Database

And a code like
```ruby
timezone = Timezone.lookup(*coordinates)
date_time = timezone.parse_local "#{date_local} #{time_local}"
```

looks more beautiful than

```ruby
timezone = Timezone.lookup(*coordinates)
date_time = Time.parse "#{date_local} #{time_local}"
date_time = Time.new(
  date_time.year, date_time.month, date_time.day, date_time.hour, date_time.min, date_time.sec,
  timezone.utc_offset(date_time)
)
```
(I even don't sure that this is correct code)

So, if you think that this method is unecessary for this gem — close this PR.

**Comment by panthomakos** [comment]
I agree the code looks more beautiful, but it's very specific to your use case, so I would recommend wrapping the functionality up into a function you can use in your own application.

Just as a practical matter, I would not recommend parsing user input using `Time.parse`. The method is very opinionated. For example, in some countries date is formatted as `DD/MM/YYYY` and in others it is formatted as `MM/DD/YYYY`. Without knowing which your user is using, `Time.parse` will either work, break, or result in an incorrect date. For example, is `11/12/2017` the 12th of November or the 11th of December?

**Comment by AlexWayfer** [comment]
> Just as a practical matter, I would not recommend parsing user input using Time.parse. The method is very opinionated. For example, in some countries date is formatted as DD/MM/YYYY and in others it is formatted as MM/DD/YYYY. Without knowing which your user is using, Time.parse will either work, break, or result in an incorrect date. For example, is 11/12/2017 the 12th of November or the 11th of December?

Thank you. Yes, I know this problem. For now, we're using international format in forms (`yyyy-mm-dd`, there is no `yyyy-dd-mm`), it's simple and accurate, but for the future, when we'll change the format in form (probably), based on user locales, this advise is helpful, thanks.

**Pull request closed without merging**
